# Generated by Django 2.2.6 on 2020-12-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forlogin',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='forlogin',
            name='mobile',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='forlogin',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='forlogin',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
