# Generated by Django 2.2.6 on 2020-12-07 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_auto_20201207_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forlogin',
            name='mobile',
        ),
        migrations.AddField(
            model_name='forlogin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
