# Generated by Django 2.2.6 on 2020-12-07 11:28

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0003_auto_20201207_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forlogin',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
